[build]
  command = "yarn generate"
  publish = "dist"

[context.v2]
  environment = { NODE_VERSION = "8" }
  command = ""
  publish = "dist"

[context.v1]
  environment = { NODE_VERSION = "8" }
  command = ""
  publish = "dist"
