backend:
  name: git-gateway
  branch: dev
media_folder: "src/static/images"
public_folder: "/images"
collections:
  - name: "notes"
    label: "Notes"
    folder: "src/content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "publishDate", widget: "datetime" }
      - {
          label: "Last updated",
          name: "updatedDate",
          widget: "datetime",
          default: "",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          field: { label: "Tag", name: "tag", widget: "string" },
        }
      - { label: "Body", name: "body", widget: "markdown" }
